// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SamuriApp.Data;

namespace SamuriApp.Data.Migrations
{
    [DbContext(typeof(SamuriDbContext))]
    [Migration("20181010031617_OneToOneTableMigration")]
    partial class OneToOneTableMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SamuriApp.Domain.Battle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("EndDated");

                    b.Property<string>("Name");

                    b.Property<DateTime>("StartDate");

                    b.HasKey("Id");

                    b.ToTable("Battles");
                });

            modelBuilder.Entity("SamuriApp.Domain.Quote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("SamuriId");

                    b.Property<string>("Text");

                    b.HasKey("Id");

                    b.HasIndex("SamuriId");

                    b.ToTable("Quotes");
                });

            modelBuilder.Entity("SamuriApp.Domain.Samuri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Samuris");
                });

            modelBuilder.Entity("SamuriApp.Domain.SamuriBattle", b =>
                {
                    b.Property<int>("BattleId");

                    b.Property<int>("SamuriId");

                    b.HasKey("BattleId", "SamuriId");

                    b.HasIndex("SamuriId");

                    b.ToTable("SamuriBattle");
                });

            modelBuilder.Entity("SamuriApp.Domain.SecretIdentity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("RealName");

                    b.Property<int>("SamuriId");

                    b.HasKey("Id");

                    b.HasIndex("SamuriId")
                        .IsUnique();

                    b.ToTable("SecretIdentity");
                });

            modelBuilder.Entity("SamuriApp.Domain.Quote", b =>
                {
                    b.HasOne("SamuriApp.Domain.Samuri", "Samuri")
                        .WithMany("Quotes")
                        .HasForeignKey("SamuriId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SamuriApp.Domain.SamuriBattle", b =>
                {
                    b.HasOne("SamuriApp.Domain.Battle", "Battle")
                        .WithMany("SamuriBattles")
                        .HasForeignKey("BattleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SamuriApp.Domain.Samuri", "Samuri")
                        .WithMany("SamuriBattles")
                        .HasForeignKey("SamuriId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SamuriApp.Domain.SecretIdentity", b =>
                {
                    b.HasOne("SamuriApp.Domain.Samuri", "Samuri")
                        .WithOne("SecretIdentity")
                        .HasForeignKey("SamuriApp.Domain.SecretIdentity", "SamuriId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
